//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Jad_Bot
{
    #region Contexts

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HelpCommandsEntities : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initializes a new HelpCommandsEntities object using the connection string found in the 'HelpCommandsEntities' section of the application configuration file.
        /// </summary>
        public HelpCommandsEntities()
            : base("name=HelpCommandsEntities", "HelpCommandsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new HelpCommandsEntities object.
        /// </summary>
        public HelpCommandsEntities(string connectionString)
            : base(connectionString, "HelpCommandsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new HelpCommandsEntities object.
        /// </summary>
        public HelpCommandsEntities(EntityConnection connection)
            : base(connection, "HelpCommandsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HelpCommand> HelpCommands
        {
            get
            {
                if ((_HelpCommands == null))
                {
                    _HelpCommands = base.CreateObjectSet<HelpCommand>("HelpCommands");
                }
                return _HelpCommands;
            }
        }
        private ObjectSet<HelpCommand> _HelpCommands;

        #endregion
        #region AddTo Methods

        /// <summary>
        /// Deprecated Method for adding a new object to the HelpCommands EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHelpCommands(HelpCommand helpCommand)
        {
            base.AddObject("HelpCommands", helpCommand);
        }

        #endregion
    }


    #endregion

    #region Entities

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "HelpCommandsModel", Name = "HelpCommand")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class HelpCommand : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new HelpCommand object.
        /// </summary>
        /// <param name="helpName">Initial value of the HelpName property.</param>
        /// <param name="helpText">Initial value of the HelpText property.</param>
        public static HelpCommand CreateHelpCommand(global::System.String helpName, global::System.String helpText)
        {
            HelpCommand helpCommand = new HelpCommand();
            helpCommand.HelpName = helpName;
            helpCommand.HelpText = helpText;
            return helpCommand;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String HelpName
        {
            get
            {
                return _HelpName;
            }
            set
            {
                if (_HelpName != value)
                {
                    OnHelpNameChanging(value);
                    ReportPropertyChanging("HelpName");
                    _HelpName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("HelpName");
                    OnHelpNameChanged();
                }
            }
        }
        private global::System.String _HelpName;
        partial void OnHelpNameChanging(global::System.String value);
        partial void OnHelpNameChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String HelpText
        {
            get
            {
                return _HelpText;
            }
            set
            {
                OnHelpTextChanging(value);
                ReportPropertyChanging("HelpText");
                _HelpText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HelpText");
                OnHelpTextChanged();
            }
        }
        private global::System.String _HelpText;
        partial void OnHelpTextChanging(global::System.String value);
        partial void OnHelpTextChanged();

        #endregion

    }

    #endregion

}
